"""Seed data: a list of intelligence report dictionaries."""

reports = [
    {
        "id": 1,
        "title": "Unusual Naval Activity in South China Sea",
        "classification": "SECRET",
        "source_type": "IMINT",
        "region": "East Asia",
        "summary": "Satellite imagery reveals three previously undetected submarine berths under construction at Yulin Naval Base. Construction appears 60% complete.",
        "date": "2026-02-14",
        "reliability": "B",
        "analyst": "GRIFFIN",
    },
    {
        "id": 2,
        "title": "Cyber Intrusion Targeting Baltic Energy Grid",
        "classification": "TOP SECRET",
        "source_type": "SIGINT",
        "region": "Eastern Europe",
        "summary": "Intercepted communications indicate a state-sponsored group is conducting reconnaissance against Lithuanian and Latvian power grid SCADA systems.",
        "date": "2026-03-01",
        "reliability": "A",
        "analyst": "CONDOR",
    },
    {
        "id": 3,
        "title": "Arms Shipment via Mozambique Channel",
        "classification": "SECRET",
        "source_type": "HUMINT",
        "region": "East Africa",
        "summary": "A reliable source reports a cargo vessel registered in Panama is transporting small arms from Iran to an undisclosed port in northern Mozambique. ETA mid-March.",
        "date": "2026-02-27",
        "reliability": "C",
        "analyst": "RAVEN",
    },
    {
        "id": 4,
        "title": "Political Instability Indicators in Caracas",
        "classification": "CONFIDENTIAL",
        "source_type": "OSINT",
        "region": "South America",
        "summary": "Open-source monitoring shows a 300% increase in anti-government social media activity in Venezuela over the past 30 days, correlating with food shortage reports.",
        "date": "2026-03-10",
        "reliability": "B",
        "analyst": "FALCON",
    },
    {
        "id": 5,
        "title": "Nuclear Facility Expansion Near Isfahan",
        "classification": "TOP SECRET",
        "source_type": "IMINT",
        "region": "Middle East",
        "summary": "New overhead imagery shows significant earthmoving activity 12 km northeast of the known Isfahan uranium conversion facility. Possible underground enrichment site.",
        "date": "2026-01-22",
        "reliability": "B",
        "analyst": "GRIFFIN",
    },
    {
        "id": 6,
        "title": "Foreign Influence Operation Targeting EU Elections",
        "classification": "SECRET",
        "source_type": "SIGINT",
        "region": "Western Europe",
        "summary": "Signals intelligence reveals a coordinated bot network operating from St. Petersburg pushing disinformation narratives ahead of upcoming French municipal elections.",
        "date": "2026-03-15",
        "reliability": "A",
        "analyst": "CONDOR",
    },
    {
        "id": 7,
        "title": "Militant Training Camp in Northern Mali",
        "classification": "SECRET",
        "source_type": "HUMINT",
        "region": "West Africa",
        "summary": "A source with direct access reports a new militant training camp near Kidal accommodating approximately 200 recruits. Training includes IED construction.",
        "date": "2026-03-05",
        "reliability": "B",
        "analyst": "RAVEN",
    },
    {
        "id": 8,
        "title": "Diplomatic Back-Channel Between Pyongyang and Tehran",
        "classification": "TOP SECRET",
        "source_type": "HUMINT",
        "region": "East Asia",
        "summary": "A senior diplomatic source confirms secret meetings between DPRK and Iranian officials in Kuala Lumpur focused on ballistic missile technology sharing.",
        "date": "2026-02-08",
        "reliability": "C",
        "analyst": "PHOENIX",
    },
    {
        "id": 9,
        "title": "Rare Earth Mineral Stockpiling by PRC",
        "classification": "CONFIDENTIAL",
        "source_type": "OSINT",
        "region": "East Asia",
        "summary": "Trade data analysis indicates China has reduced rare earth exports by 40% while increasing domestic stockpiling, suggesting possible preparation for export restrictions.",
        "date": "2026-03-18",
        "reliability": "A",
        "analyst": "FALCON",
    },
    {
        "id": 10,
        "title": "Unidentified Submarine Contact in Norwegian Sea",
        "classification": "SECRET",
        "source_type": "SIGINT",
        "region": "Northern Europe",
        "summary": "Acoustic sensors detected an unidentified submarine transiting the GIUK gap at low speed. Signature does not match known NATO or allied vessels.",
        "date": "2026-03-22",
        "reliability": "B",
        "analyst": "CONDOR",
    },
    {
        "id": 11,
        "title": "Fentanyl Precursor Shipments Through Guatemala",
        "classification": "SECRET",
        "source_type": "HUMINT",
        "region": "Central America",
        "summary": "A vetted source reports Chinese-manufactured fentanyl precursors are being routed through Puerto Quetzal to Mexican cartel-linked labs in Sinaloa.",
        "date": "2026-01-30",
        "reliability": "B",
        "analyst": "RAVEN",
    },
    {
        "id": 12,
        "title": "Satellite Jamming Tests Over Taiwan Strait",
        "classification": "TOP SECRET",
        "source_type": "SIGINT",
        "region": "East Asia",
        "summary": "Electronic intelligence confirms PLA units conducted GPS jamming exercises across a 200 km corridor in the Taiwan Strait over a 72-hour period.",
        "date": "2026-03-08",
        "reliability": "A",
        "analyst": "CONDOR",
    },
    {
        "id": 13,
        "title": "Attempted Recruitment of NATO Official in Brussels",
        "classification": "SECRET",
        "source_type": "HUMINT",
        "region": "Western Europe",
        "summary": "Counterintelligence reports a Russian intelligence officer operating under diplomatic cover approached a mid-level NATO logistics planner at a social event.",
        "date": "2026-02-19",
        "reliability": "A",
        "analyst": "PHOENIX",
    },
    {
        "id": 14,
        "title": "Drought-Driven Migration Surge in Horn of Africa",
        "classification": "CONFIDENTIAL",
        "source_type": "OSINT",
        "region": "East Africa",
        "summary": "UN and NGO reporting indicates over 500,000 displaced persons are moving toward the Kenyan border from southern Ethiopia and Somalia due to prolonged drought.",
        "date": "2026-03-12",
        "reliability": "A",
        "analyst": "FALCON",
    },
    {
        "id": 15,
        "title": "Weapons Cache Discovery in Eastern Ukraine",
        "classification": "SECRET",
        "source_type": "IMINT",
        "region": "Eastern Europe",
        "summary": "Commercial satellite imagery shows a previously unreported vehicle depot near Donetsk with thermal signatures consistent with recently delivered heavy armor.",
        "date": "2026-02-25",
        "reliability": "B",
        "analyst": "GRIFFIN",
    },
    {
        "id": 16,
        "title": "Cryptocurrency Laundering Network in Southeast Asia",
        "classification": "SECRET",
        "source_type": "SIGINT",
        "region": "Southeast Asia",
        "summary": "Intercepted traffic links a network of crypto exchanges in Cambodia and Myanmar to DPRK-affiliated wallets laundering an estimated $120M over six months.",
        "date": "2026-03-20",
        "reliability": "B",
        "analyst": "CONDOR",
    },
    {
        "id": 17,
        "title": "Biolab Security Concerns in Central Asia",
        "classification": "TOP SECRET",
        "source_type": "HUMINT",
        "region": "Central Asia",
        "summary": "A source within the Kazakh Ministry of Health reports deteriorating safety protocols at a Soviet-era biological research facility near Almaty storing dangerous pathogen samples.",
        "date": "2026-01-15",
        "reliability": "C",
        "analyst": "RAVEN",
    },
    {
        "id": 18,
        "title": "Anti-Satellite Weapon Test Preparations",
        "classification": "TOP SECRET",
        "source_type": "IMINT",
        "region": "South Asia",
        "summary": "Imagery of a known Indian missile test range shows launch pad preparations consistent with a direct-ascent anti-satellite weapon test observed in previous cycles.",
        "date": "2026-03-25",
        "reliability": "B",
        "analyst": "GRIFFIN",
    },
    {
        "id": 19,
        "title": "Hezbollah Tunnel Network Expansion",
        "classification": "SECRET",
        "source_type": "IMINT",
        "region": "Middle East",
        "summary": "Updated imagery analysis reveals new tunnel entrance points along the southern Lebanese border, suggesting a 30% expansion of the known underground network.",
        "date": "2026-02-03",
        "reliability": "B",
        "analyst": "GRIFFIN",
    },
    {
        "id": 20,
        "title": "Arctic Military Base Construction by Russia",
        "classification": "CONFIDENTIAL",
        "source_type": "OSINT",
        "region": "Northern Europe",
        "summary": "Commercial shipping and open-source imagery confirm accelerated construction of a new Russian military facility on Franz Josef Land, including an extended airstrip.",
        "date": "2026-03-02",
        "reliability": "A",
        "analyst": "FALCON",
    },
]
